### ISSUE TITLE
How do things go in the world of systemd-homed?

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [maisiliym/mkUniksOS#1]
Hi, I noticed this lil bit in your config:
https://github.com/maisiliym/mkUniksOS/blob/2d2fffeff718f17f5a876f662b3f1b749c294386/normylaiz.nix#L69-L73

A while back I created an issue on nixpkgs about systemd-homed, today conversation came up on NixOS discord and thought to check up on all of it (see if anyone put some elbow grease into it :D )

What i am interested in:
- Are you using it or is it there just for the show?
- If you are using it - I assume you use it as the normal run of the mill `users.mutableUsers = true;`?

**EDIT:** renamed issue due to emojis not rendering in title :(

**Comment by johnrichardrinehart** [comment]
[The aforementioned issue](https://github.com/NixOS/nixpkgs/issues/91243).

**Comment by maisiliym** [comment]
Its moved to github:maisiliym/uniks. Still in prerelease preview. Personal  daily driver with various unpleasant bugs which the designer lives with. Nix code is to be soon redone in shen. Porting shen adaptation inside and around nix, called uniks.
